### PR TITLE
Fix errors in commit 156d2b8 and 053ebfe

### PR DESCRIPTION
**Pull request by FridoDeluxe**
both commits led to build failure, it's fixed now

### CODE REVIEW

**Comment by robinpaulson** [comment]
My bad, cheers for fixing those

**Comment by FridoDeluxe** [comment]
Due to the GitHUb Actions I got notifies about the build errors, very convenient.

Just a question: Do you have no possibilities to compile/test changes before commit?

**Comment by robinpaulson** [comment]
Sloppiness and hubris. I assumed it was so minor I didn't need to check it.

**Comment by FridoDeluxe** [comment]
Happens to everyone often enough :smile:

**Pull request merged**
