### PR TITLE
Add Korean Guide Document and LICENSE.ko

### PR DESCRIPTION
**Pull request by jangsik2**
Hello, I confirmed that the last Pull request was merged. Thank you. This time, I made a guide for using the new app in Korean. And I translated LICENSE into Korean version so that Koreans can see it easily. please check if Merge is possible:)!!

### CODE REVIEW

**Comment by robinpaulson** [comment]
OK, I have two questions: did you translate the GPL document yourself, or obtain it from the GNU project? Given that it's a legal document, I'm wary of meaning being lost/confused, so will only accept the latter.

Secondly, I'm not sure about the guide, whether it's necessary. There was an offer to write an FAQ/help file some months ago which didn't come to anything, perhaps that would be more appropriate?

**Comment by robinpaulson** [comment]
As an aside, I'll only accept a non-binary version, maybe in markdown or html? Assuming it's accepted that is.

**Comment by jangsik2** [comment]
Okay. I think again and write a Pull request!!

**Comment by robinpaulson** [comment]
Looking at this page it appears the licence is not published by GNU/FSF in Korean:
https://www.gnu.org/licenses/licenses.html
I am interested in a FAQ/help page in Korean though, as I am in any language.

**Comment by robinpaulson** [comment]
I'm going to close this, due to the reasons listed above.

Perhaps we should write a FAQ in English first, then work on translations to other languages? Starting in Korean then using that as a base for other languages sounds difficult.

**Pull request closed without merging**
