### PR TITLE
Add Hungarian translation

### PR DESCRIPTION
**Pull request by isti03**

### CODE REVIEW

**Comment by robinpaulson** [comment]
Wonderful, another translation!

It'd be great if you were able to translate the README too; #625.

**Comment by isti03** [comment]
Would that be useful to anybody? Who sees the translated README?

**Comment by robinpaulson** [comment]
Anyone who comes to the Github page is likely to see it. It's partly symbolic, as a small way of welcoming the non-Anglos and of encouraging other contributors to think of who might be using the software.

**Comment by isti03** [comment]
I believe it just increases clutter with barely any benefit, since mostly
technical, English-speaking people will visit the GitHub page, not the
average user.

However, translating the store page(es) will have an actual impact on the
end user and I would be glad to do it if there was an option.

With that said, I might translate the Readme in the future.

**Comment by robinpaulson** [comment]
> it ... increases clutter

At best that's a disappointing attitude towards non-English speakers, to hear that aspects of their culture are considered "clutter". I'll request you read the CODE-OF-CONDUCT.md before taking this conversation any further.

> mostly technical, English-speaking people will visit the GitHub page

I'd like to see something to back that up. Even if it is true, it still supports the point I'm making. Saying "only english-speakers come, we only need to provide for them" is the problem, not the solution. How will we ever encourage that to change if we don't do anything to assist it, such as translating resources? Small steps shouldn't be dismissed because they're "not big enough".

The fastlane file structure provides for showing different README, etc. files to different language speakers. At the moment the bare minimum (en-US) is provided in Forecastie; expanding it would be a good idea.

https://gitlab.com/-/snippets/1895688

**Comment by isti03** [comment]
> that's a disappointing attitude ... that aspects of their culture are considered "clutter". 

As a translator, I wouldn't believe that aspects of one's culture are considered clutter. I have read the CoC and I believe I haven't discriminated against anyone. What I mean by clutter is that having a README file for every language lengthens the file listing at the top of the page by a considerable amount. 

All the while as a non-technical user, one probably has very little idea, that they have to search for a `README.*.md` file. The only exception I would see is if the translated README gets indexed by a search engine, but I see a small likelihood of someone finding the project that way. 

> Saying "only english-speakers come, we only need to provide for them" is the problem, not the solution. 

I believe that the source conflict stems from the difference between our opinions on GitHub. You look at GitHub as more than a place for just collaborators, while I don't. From my perspective of GitHub as a place for technical people, it makes sense that we only need to provide for English-speakers, since that is the common language of collaboration. I believe that GitHub would be more than a platform for technical people if:

- the UI would be localized (or at least the parts of the public repo page)
- the README would be shown before the files and an appropriate localized README would be shown if available
- issues were handled in multiple languages
- people could discover software based on their platform of choice and categories

I'm not sure whether we will come to terms regarding this issue, but I will translate the store page and try to help encourage other translators to do so by updating `CONTRIBUTING.md`.

**Pull request merged**
