### PR TITLE
add a predefined, longhand datetime format

### PR DESCRIPTION
**Pull request by jawz101**
ex: Monday, February 18, 4:09pm

### CODE REVIEW

**Comment by jawz101** [comment]
I think this triggers a crash due to https://github.com/martykan/forecastie/issues/287.  Personally, I'd just not have any expectations of what we put in there and let java's date thing consume what we put in.  Maybe have a little description on the custom date window below it that just shows the valid characters `aDdEFGHhKkMmSsuWwXYyZz`

**Comment by robinpaulson** [comment]
@jawz I agree entirely, we should fix #287 ASAP.

**Comment by robinpaulson** [comment]
@jawz101 Given the acceptance of the latest PR to fix the date format crashing problem, I would like reopen this and accept, assuming no problems. I see the repo which the pull is from has been deleted; would you be able to ressurect it?

**Comment by robinpaulson** [comment]
Actually, maybe I just copy and paste it in, it's a pretty simple change.

**Pull request closed without merging**
