### PR TITLE
Change to Match the format required by the API

### PR DESCRIPTION
**Pull request by yonniii**
image

### CODE REVIEW

**Comment by robinpaulson** [comment]
Could you fix the formatting, so they are laid out the same way? I'm a big fan of tidy, neat code, it helps readability no end.

**Comment by robinpaulson** [comment]
Also on a similar not, I reopened #388, see my comment there before you do this.

**Comment by yonniii** [comment]
I added commits, Please check it!

**Comment by robinpaulson** [comment]
There are still some stray spaces and misalignments. Also, please check #338

**Comment by yonniii** [comment]
Do I still miss anything?

**Comment by robinpaulson** [comment]
Sorry, i meant #388, please check the last comment I made and see if you can answer it.

The next release won't be out for at least a week, so there's no hurry to finish this, we've got plenty of time.

**Comment by robinpaulson** [comment]
Sorry, this slipped my mind.

**Pull request merged**
