### PR TITLE
Fix overlapping items on main screen

### PR DESCRIPTION
**Pull request by yuhuitech**
Dear developer:

Hello! I am the creator of issue #601, and I have fixed the display issues I mentioned before. Because there are too many strings on this page and I do not want to remodel the XML structure too much, so I used "dp" instead. I would genuinely appreciate it if you could kindly revise my code and leave me some advice. Thank you so much for your precious time!

Here are the screenshots after my changes:

copy  copy copy

Thanks again! Blessings on your day! :)

### CODE REVIEW

**Comment by robinpaulson** [comment]
would you be able to test this on devices/emulators of varying resolutions? i'm wary of what this will do on other screen sixes

**Comment by yuhuitech** [comment]
OK. I would like to test it.  :)

**Comment by robinpaulson** [comment]
What's the difference between sp and dp?

**Comment by robinpaulson** [comment]
It is a good idea though, i'll be glad to accept this once we've seen how it affects the layout. As a side not, some of the longer description strings overlap the icons, it would be excellent if this fixed that too. i'll have a look for the issue later and post it here

**Comment by yuhuitech** [comment]
Using dp will grant that the text would stay a small and apt size which could make sure those texts don't overlap with other texts. But using sp will make the texts grow with the display size and might exceed its border and overlap other texts.

**Comment by robinpaulson** [comment]
#540 is the issue with clashing icon and text

**Comment by yuhuitech** [comment]
Hello! I just tested my code on an emulator of Pixel 3 XL (1440x2960) with API 29, and it works fine for me. Here is the screenshot:

copy

**Comment by robinpaulson** [comment]
TOMORRO
       W

**Comment by yuhuitech** [comment]
I did not change the text size of the "TOMORROW" in my modification. So this should be an automatic line shift.

**Comment by yuhuitech** [comment]
But as far as I am concerned, this might be a rather small problem, because we could still see all of the characters of TOMORROW.

**Comment by yuhuitech** [comment]
If you find it troublesome, I guess maybe I could fix this too. :)

**Comment by robinpaulson** [comment]
> I did not change the text size of the "TOMORROW" in my modification. So this should be an automatic line shift.

huh, interesting. what's the resolution of your screen?

**Comment by yuhuitech** [comment]
I use two resolutions now. The former screenshots I showed you are from PIcel 2 with a resolution of 1080x1920.
The latter one is Pixel 3 XL with a resolution of 1440x2960.

**Comment by robinpaulson** [comment]
> I use two resolutions now. The former screenshots I showed you are from PIcel 2 with a resolution of 1080x1920.
> The latter one is Pixel 3 XL with a resolution of 1440x2960.

that is odd. my galaxy has a much smaller res but doesn't mangle "TOMORROW"

**Comment by yuhuitech** [comment]
Really? Could you show me the screenshot? I am intrigued by this one. :)

**Comment by yuhuitech** [comment]
Or have you set your text size to the largest as well?

**Comment by robinpaulson** [comment]
> Or have you set your text size to the largest as well?

it's all default settings. i use lineage 15

**Comment by robinpaulson** [comment]
720 px wide

**Comment by robinpaulson** [comment]
i wonder how much of this is due to an odd font size setting on your device? i think there are some things worth fixing anyway, to cover for others with the same situation

**Comment by yuhuitech** [comment]
Oh, the latter screenshot I showed you also came from a device with the largest font size and display size. So that is why the "TOMORROW" is broken into two lines.

**Comment by yuhuitech** [comment]
You can set display size and font size on those two pages, and they are both inside the settings app:

copy copy

**Comment by yuhuitech** [comment]
Here is my testing on the Pixel 3 XL with the largest font size and the normal display size. As you could see the TOMORROW is also normal now, just like your Galaxy phone.

copy

**Comment by robinpaulson** [comment]
Excellent!

**Comment by robinpaulson** [comment]
> i wonder how much of this is due to an odd font size setting on your device? i think there are some things worth fixing anyway, to cover for others with the same situation

sorry for asking a silly Q, i realised i had missed some important info in your well-written bug report. i read it again, the situation is much clearer now

**Comment by fAntel** [comment]
@yuhuitech Hi. Here is a quote about sp from Android documentation ([link](https://developer.android.com/training/multiscreen/screendensities))
> The sp unit is the same size as dp, by default, but it resizes based on the user's preferred text size.

So yes, when you swap sp with dp they became smaller because they do not scale based on your system the largest text size anymore.
This is how preview of this screen looks like with sp:
image
And this is with dp:
image

I am not saying this because such a change is not worth doing, but to clarify how it works. If you use the largest text size every day and Forecastie with dp looks readable, then maybe sp is overlooked, and it's usage just a habit. :)

**Comment by yuhuitech** [comment]
@fAntel Thank you so much for your detailed illustrations on this. I think that use dp could alleviate this kind of a11y problems such as texts being blocked or overlapping texts. And as far as I am concerned it will also reduce the amount of changes we apply to the XML files, which would not hurt the basic structure of the XML file too much and it could reach the readable goal as well.

I also think using dp is viable because though using dp will make the texts smaller, it will make sure the texts will not be occluded and users still have the possibility to see all of the characters inside those strings. But when it comes to sp, users might not be able to see all of them if the texts or icons are blocked partly or totally, which might affect the user experience as well.

That is my opinion. :)

**Comment by robinpaulson** [comment]
The discussion between @fAntel and @yuhuitech sounds like it's heading towards one of two situations:
1. the text being difficult to read because it's too small,
2. the text being difficult to read because there are overlaps.
This is a valid conversation. I wonder though if we can satisfy both a11y problems by some other means? The obvious, but maybe not best solution, is to rearrange the screen so larger text does not overlap with other items.

**Comment by franklinbill** [comment]
I think it might be better to use dp in the current situation 👍 @yuhuitech

**Comment by fAntel** [comment]
There is issue about redesign of UI. I think the dp solution is better now until the redesign issue will be developed.

**Comment by robinpaulson** [comment]
@yuhuitech Where are we at with this? I Have got tangled by the conversation shifting topics. What do you think, based upon the conversations we had?

**Comment by yuhuitech** [comment]
@robinpaulson Hello, I think we could apply flex layout in this kind of situation, and I have already made some modifications to it, and I will show you the screenshots later.

**Comment by yuhuitech** [comment]
copy copy

I used Flexbox from google to make those views more adaptive when space is not enough. And I did not change the text size as well, they are all in sp. If you don't want to use Flexbox, constraint layout (version > 2.0) could achieve this as well with flow_wrapMode="chain".

Later I will show you my code, sorry for the late.

**Comment by robinpaulson** [comment]
Late is not a problem, any contributions at any time are welcome and appreciated.

I don't know Flexbox, so long as it fulfils the licence requirements, is stable and not a gigantic size, then we'll use it.

**Comment by yuhuitech** [comment]
@robinpaulson, I have pushed my latest change, and you can run this code to see the final effect. Also, I fixed a bug when viewPager is reset with another new adapter after refreshing, this AppBarLayout will lose its focus and become unclickable and un-scrollable.

I think this is better:
```
        if(this.pagerAdapter == null) {
            pagerAdapter = viewPagerAdapter;
            viewPager.setAdapter(pagerAdapter);
            tabLayout.setupWithViewPager(viewPager);
        }
        pagerAdapter.notifyDataSetChanged();

        int currentPage = viewPager.getCurrentItem();

        if (currentPage == 0 && longTermTodayWeather.isEmpty()) {
            currentPage = 1;
        }
        viewPager.setCurrentItem(currentPage, false);
```

**Comment by robinpaulson** [comment]
So, this will leave the layout as it is, unless the user selects a large font size at the system level? Is that correct?

**Comment by yuhuitech** [comment]
Yes, when the normal display size and font size are applied, the layout is still the same as before. If the largest font and display size are applied, the flex layout will take effect.

**Comment by robinpaulson** [comment]
Github is complaining that there is a conflict, I think it's because you've used single quotes around the import of flexbase. Could you take a look at it?

**Comment by robinpaulson** [comment]
in app/build.gradle

**Comment by yuhuitech** [comment]
OK, I saw this problem. I will change it right now.

**Comment by robinpaulson** [comment]
Huh, looks like something else. Do the libraries clash with each other?

**Comment by robinpaulson** [comment]
We're getting a build failure, something wrong with the layout, in "list.xml".

https://github.com/martykan/forecastie/runs/4338200046?check_suite_focus=true

**Comment by yuhuitech** [comment]
@robinpaulson  Sorry, the "xmlns:app="http://schemas.android.com/apk/res-auto" is missing. I just added this namespace to this XML file.

**Comment by robinpaulson** [comment]
@yuhuitech I had to remove all your code for this, it severely broke the UI and took much wrangling to put right - assuming it is fixed, we'll know in a day or two. It would have been a big help if you'd responded when I asked.

**Pull request merged**
