### PR TITLE
Updated catalan translation

### PR DESCRIPTION
**Pull request by adriaaah**
This includes not only some minor fixes but also new strings that
weren't added.

Strings are also organised into sections.

### CODE REVIEW

**Comment by robinpaulson** [comment]
Excellent, good to see the strings reordered!

**Comment by robinpaulson** [comment]
There were a few problems in the strings.xml file; nothing complicated, mostly unescaped apostrophes. I'm going through, fixing them as the build process fails and throws errors. I'm pleased with the overall PR though, it's good to keep the translations up-to-date. :-)

**Comment by adriaaah** [comment]
Didn't notice these problems you detected. I'm open to go through them if you can't, just let me know it.
Thanks!

**Comment by robinpaulson** [comment]
Thanks for the offer, Github's CI build setup was good at pointing out the errors, so by trial-and-error I got them all.

**Pull request merged**
