### PR TITLE
Use real sunrise and sunset times to select day/night weather icons. Fix error in ko translation

### LINKED ISSUE #373: Consider real sunrise and sunset to determine daytime
https://github.com/martykan/forecastie/blob/5b225acdfdecebdd4a581363a0efe47e29dc22bb/app/src/main/java/cz/martykan/forecastie/utils/Formatting.java#L138

Use `getSunrise()` and `getSunset()` methods from `Weather` class.

### PR DESCRIPTION
**Pull request by igor-cali**

### CODE REVIEW

**Comment by FridoDeluxe** [comment]
@igor-cali Thanks, I also was bothered by the fixed sunrise and sunset hours. But I have a few remarks:

1. Is this code really working, especially for the 5-day-forecast icons? You are using `Calendar now = Calendar.getInstance();` so every icon seems to be adjusted to the current time ...
2. Has anybody seen sunrise/sunset times in the OWM data of the 5-day-forecast at all? Their [API](https://openweathermap.org/forecast5) doesn't state it and I could find it either in the actual JSON responses. In my opinion it would be nice if we could find a solution for all icons and not only the current weather.
3. Do you really want to merge code with this style (old code not deleted, but in comments; lower-case class name `timeUtils.java`) or have you forgotten to tidy things up?

**Comment by igor-cali** [comment]
@fridodeluxe thanks for your comments.

1/2: sunset and sunrise times do not change that much in 5 days (depending on latitude, of course).
By the way: the isDayTime function I added falls back to the old check (between 7 AM and 8 PM) when sunset and sunrise time are not set, which is the case for the next days forecast (according the debug I made).
3: I just wanted to clearly show the changes I made. I can tide them up shortly, of course.

Please let me know.

**Comment by FridoDeluxe** [comment]
I agree that sunrise/sunset does not change that much in five days so it's viable to use the same times for several consecutive days.

1. In this case I am rather worried about the **time** than the **date**. I think `isDayTime()` will introduce a new bug and render all icons according to the current time. It can be reproduced like this: Use a location with clear sky for the upcoming days (e.g. Los Angeles) and you'll see that all icons of the 5-day-forecast will have the same icon - either day or night depening on your current time. Is it understandable what I mean or am I wrong?
2. The OWM 5-day-forecast apparently has no sunrise/sunset data, so the fallback will always be used which is no improvement over the current situation. Since the sunrise/sunset time does not change that much it would be nice to somehow use this information also for the forecast. But this does not need to be included in this merge request.
3. Great :+1: I just wanted to prevent unfinished code from being merged. Just my opinion, in the end it's up to the person in charge of merging what code style requirements are applied. Still I wonder why you don't capitalize class names ...

**Comment by igor-cali** [comment]
Now I see your comment 1.
Let me rework the code.

**Comment by igor-cali** [comment]
It should work now (see 1st and 3rd icon in the sceenshot).

Schermata del 2019-11-03 23-51-22

**Comment by robinpaulson** [comment]
Looks good; @FridoDeluxe I accept your points about coding style, thanks for pointing them out, I think it is important.

**Comment by FridoDeluxe** [comment]
@igor-cali Nice work, also fixing the error in korean translation.

I neither wanted to denigrate this PR in any way nor start a discussion about code style. But generally I think as well that the code base will benefit from meeting some style standards.

Concerning the capitalization of class names: I mean UpperCamelCase which is a [well established convention for Java](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Java).

**Comment by igor-cali** [comment]
@FridoDeluxe no problem for me. Class name style adapted.

**Comment by robinpaulson** [comment]
That's great folks, I'll approve this PR now. Cheers for the excellent contributions.

**Comment by robinpaulson** [comment]
Perhaps we should append info on the preferred style guide to the CONTRIBUTING.md file? @FridoDeluxe , would you be willing to write a line or two, it sounds like you know some good info here?

**Comment by azakosath** [comment]
I don't know if this merged pull-request is the reason, but after v.1.10.9 widgets and the main screen always show night icons, the rest forecast is ok. Am I the only one having this bug? It's strange that nobody reported this so far.
IMG_20191122_113925
IMG_20191122_113850

**Comment by igor-cali** [comment]
@azakosath thanks. I will take a look during the weekend.

**Comment by igor-cali** [comment]
Opened issue #399 / PR proposed.

**Comment by robinpaulson** [comment]
Thanks @azakosath for reporting this.

**Pull request merged**
