### PR TITLE
Add support for percent of precipitation

### LINKED ISSUE #79: Feature Request: % Chance of Rain
It would be helpful to see a % chance of rain on the forecasts. An extremely low possibility of rain on other apps/services will still just show 'rain' on Forecastie

### PR DESCRIPTION
**Pull request by shortspider**
Fixes #79.

### CODE REVIEW

**Comment by robinpaulson** [comment]
Hi @shortspider this is great, I'm pleased to see this. How does it display, I couldn't work it out from looking at the code?

**Comment by shortspider** [comment]
@robinpaulson I've renamed to chance. Here is a screenshot from the emulator:
image

**Comment by robinpaulson** [comment]
Excellent, thanks for that! I see why you chose the original variable name now, OWM calls it "pop".

**Comment by robinpaulson** [comment]
@shortspider I had to do a git reset today, after another coder broke the GUI with a bad commit. Could you re-propose this for merge? My git fu is not so great and I fear my brain can't take learning how to do it all from this end.

**Comment by shortspider** [comment]
@robinpaulson it looks like all the code is still there:
image`

**Comment by robinpaulson** [comment]
Hi, yes, I made (another) mistake. After doing the hard reset, I remerged your contribution, not realising it would pull in a series of other commits which were the cause of the app breaking. I've since done another hard reset to remove the breaking code again, which has also removed your commits. I need to learn more about Git, there's lots I don't understand.

**Comment by shortspider** [comment]
@robinpaulson I've had to create a new PR, please review #631.

**Pull request merged**
