### PR TITLE
Added German notification translations to strings.xml

### PR DESCRIPTION
**Pull request by schirinowski**
Added German notification translations

### CODE REVIEW

**Comment by sotpapathe** [comment]
Thanks for helping translate forecastie!

The translation strings are now split over multiple files. You can see the new string organization in the English translation in `app/src/main/res/values/string*`. Following the English string layout, the German notification strings should be in `app/src/main/res/values-de/strings_notification.xml`. Thus please create this file and move your newly added strings there. After that the PR should be merged!

For future reference, there is a Python3 script to help with translating. To see the current state of the German translation run `./tools/translation-progress.py -v -m de`. The output should be something like

``` text
Language: de
  File:           values-de
  Translated:     126 ( 80%)
  Not translated:  20 ( 12%)
  Missing:         10 (  6%)
  Misplaced:      146 (100%)
  Completion:      80%
```

Misplaced means that the translated strings are in the wrong file, as is the case in your PR. If you add another `-v` option it will show which exact strings fall in each category.

**Comment by schirinowski** [comment]
Thanks for clarification. Wasn't sure what the actual procedure for translation is. Did I overlook the guidelines?

What confused me about the Python script as well: the Python script link in https://github.com/martykan/forecastie/blob/master/CONTRIBUTING.md#translations gives a 404, so I thought it's not relevant anymore. 😬

**Comment by sotpapathe** [comment]
Ah, maybe the guidelines haven't been updated, I'll do that. Thanks for pointing out the 404, I'll fix that too.

**Comment by schirinowski** [comment]
Excellent, thanks!

**Comment by robinpaulson** [comment]
@schirinowski Great to have you on board, cheers for the translations!

My bad for not keeping the guidelines up-to-date, I'll take a look at the problems you pointed out.

**Comment by schirinowski** [comment]
Happy to contribute! 😊

**Pull request merged**
