### PR TITLE
increase build/version number

### PR DESCRIPTION
**Pull request by robinpaulson**
to inlcude various minor fixes and improvements over the last few months

### CODE REVIEW

**Comment by ildar** [comment]
Plz don't forget to tag. Otherwise F-Droid won't build it

**Comment by robinpaulson** [comment]
@ildar If i recall correctly, the f-droid build tool automatically searches for build/version numbers at various places in the repo, including AndroidManifest.xml and possibly also build.gradle. Hence why I made the pull request to only change build.gradle.

**Comment by ildar** [comment]
Not in this case.
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/cz.martykan.forecastie.txt
Tags are friends 😀

**Comment by robinpaulson** [comment]
Hmm, I wonder if there is a delay for some other reason? E.g., does the f-droid build tool poll the various repositories for updates (if so, how often?), or is it interrupt driven, by the repositories requesting an f-droid pull any new changes? I would imagine the former, but I don't have a knowledgeable answer.

That said, yes tags are great.

**Comment by ildar** [comment]
Checks are daily.

**Comment by robinpaulson** [comment]
I tagged v1.3 it will be in fdroid in a day or so

**Comment by relan** [comment]
Git tag should correspond to version name or F-Droid will not add a new build automatically. In Git, tag removal does not cause history rewrite. Could you please delete both `1.3` and `v1.3.1`, and re-tag `v1.3`? This will clean everything up without the need to do anything on F-Droid side to fix [Git checkout of 'v1.3' failed](https://f-droid.org/wiki/page/cz.martykan.forecastie/lastbuild_15) error.

**Comment by robinpaulson** [comment]
@relan cheers for the advice, I will fox shortly

**Comment by robinpaulson** [comment]
I appreciate the assistance relan, I got in a bit of a tangle with tags. I am confident it is fixed now, lessons learned for the next release!

**Comment by robinpaulson** [comment]
Hi @relan It turns out there were other unrelated build errors from a couple of the translations in v1.3, since fixed. I brought forward the release of v1.4, I presume it will also be automerged into the f droid repository in the next day or so.

**Comment by relan** [comment]
Correct. Note that currently there are issues on F-Droid's side, so it may take more than a day or two.

**Pull request merged**
