### PR TITLE
add translate ko

### PR DESCRIPTION
**Pull request by Ryeoly**
I am a member of the same team as byoung-min who raised the issue for translate.ko.
Added array.xml and changed string.xml to change units of refresh background interval.
 Please check!!! :)

### CODE REVIEW

**Comment by robinpaulson** [comment]
What do we gain by adding array.xml, it appears to be entirely in English (I'm not knowledgeable enough to understand so much about app programming)?

**Comment by Ryeoly** [comment]
translate
We have coded for this partial translation. If our code is a problem, can you tell me how to change it?
In arrays.xml we added the @string part  and  in strings.xml we just added the place for that part.
array(xml)
strings(xml)

**Comment by FridoDeluxe** [comment]
@Ryeoly You have copied the `arrays.xml` to translate the update intervals. But this way all values are duplicated which is redundant, also no other languages can't benefit from the translation possiblity.

A better approach would be to add the new string (`settings_15min` etc.) to the default `arrays.xml`. Then include a default english translation (preferably like the existing hardcoded one) to `strings.xml` and keep your korean translation.

**Comment by robinpaulson** [comment]
@FridoDeluxe Thanks for explaining that better than I could have done.

**Comment by robinpaulson** [comment]
@FridoDeluxe If I cherry-pick "strings.xml" and ignore "arrays.xml" will that create any problems?

**Comment by robinpaulson** [comment]
I'll make a new release now. @Ryeoly If you can fix up based on fridodeluxe's comments, I will accept this into the next release in a couple of weeks.

**Comment by FridoDeluxe** [comment]
@robinpaulson No, cherrypicking won't work because both the current default `strings.xml` and the `arrays.xml` do not support translated update intervals. They are hard coded right now, so there is nothing using the korean translation values.

**Comment by robinpaulson** [comment]
Closing for now, I will reopen and accept once the changes suggested by fridodeluxe are made.

**Pull request closed without merging**
