### PR TITLE
Layout rework of 4x1 time widget

### PR DESCRIPTION
**Pull request by abika**
...so that all the content really fits into a 4x1 block.
Tested with mdpi, hdpi and xxdpi emulator screen size.

Screenshot (hdpi; same widget with 4x1 size and expanded to 4x2 size): 
screenshot_1490897795

Mentioned in #51 and #68.

---
Bonus: fixed an IndexOutOfBoundsException.

### CODE REVIEW

**Comment by ildar** [comment]
Awesome!

**Comment by ildar** [comment]
🙁
I don't see 4x1 widgets, only 5x2 in version 1.4
Could someone please shrink minimum size to 4x1 or even smaller? 5x2 are
really dispersed.

**Comment by robinpaulson** [comment]
Yep, me too. There is less info in the new widget, so it could be smaller (4x1)
@abika Could you take another look and see what went wrong?

**Comment by abika** [comment]
I cannot reproduce this. I have the 4x1 widget like in the screenshot above and tested it with different screen settings. 
What screen size/resolution do you have? Can you provide screenshots?

**Comment by abika** [comment]
Can you post a screenshot and your screen settings (size and resolution)? I'll try to adjust the space again.

**Comment by ildar** [comment]
screenshot_20170712-091232

**Comment by ildar** [comment]
$ adb shell dumpsys window | grep dpi
    init=720x1280 320dpi cur=720x1280 app=720x1280 rng=720x672-1280x1232

**Comment by abika** [comment]
320dpi -> xhdpi; ~4.65'' at 720x1280. I tried with these settings but its still a valid 4.1 widget for me.
I also wanted to test it with Android 7.1.1/API 25 instead of Android 4.4/API 19 but the vm does not start on my Linux machine for some unknown reason:/

screenshot_1500207744

And still: all size values I changed are in dp/sp units like the docs recommend. It shouldn't look different depending on screen settings.

**Comment by ildar** [comment]
Do you notice that the widgets get the whole width: the width that's
occupied by the five icons in the bottom? Hence the widget is 5 in width?

**Comment by abika** [comment]
Nope, it's 4x1 for me.

[screenshot_1500401775](https://user-images.githubusercontent.com/1074117/28489705-0e312c96-6ec9-11e7-9a30-43f964a55d1c.png)
[screenshot_1500407307](https://user-images.githubusercontent.com/1074117/28489709-48681352-6ec9-11e7-847d-b62d6f074d95.png)

Though, it's possible that the widget gets the whole width and expands to 5 cells. However, more important is the height of 2 cells instead of 1. I could simply reduce the minimum height set here but I will not be really able to test it.

**Comment by ildar** [comment]
May it be Launcher-related? Could you please try Catapult or any other
Trebuchet-based launcher? Thanks!

**Pull request merged**
