### PR TITLE
More colourful app icon

### PR DESCRIPTION
**Pull request by Karandeep98**

### CODE REVIEW

**Comment by robinpaulson** [comment]
Hi @Karandeep98, it's good to know you are interested in the project, new developers are always welcome.

I am fine with receiving out-of-the-blue changes as a PR, although I'm not keen on the words "improved" and "updated" as the sole descriptors. Could you tell me a little more about the changes, perhaps why you think they are important? Thanks

**Comment by robinpaulson** [comment]
I looked at the icons, they are nice, I like the colours. Hmm, I'm not sure what to do. I shall ask others on the Issues, I'm never keen on making changes unilaterally.

**Comment by FridoDeluxe** [comment]
A technical remark: The changed gradle files should not be part of this pull request.

I'll write down my thoughts concerning the icon in #470 in the next days.

**Comment by robinpaulson** [comment]
This is a good point, frido. @Karandeep98 Could you split the PR into two please? One for the icons, one for the gradle files? Cheers

**Comment by FridoDeluxe** [comment]
Also I don't understand the meaning of `app\src\main\res\drawable\ic_launcher_background.xml`, is it necessary for anything?

**Comment by fAntel** [comment]
It's used as background on Android Oreo (8) and above.
More info: [Adaptive Icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive)

**Comment by FridoDeluxe** [comment]
@fAntel thank you for the information, unfortunately I'm not that experience with adaptive icons.

I was asking because the actual content of `ic_launcher_background.xml` is just the generic grid. I was wondering if it's necessary to include that in the repository?

**Comment by fAntel** [comment]
It is generated when pictures is added as icon. So when it will be needed for build, having it in the repository is better than add the icon again.

**Comment by robinpaulson** [comment]
As per the discussion in #470, closing and not accepting. Cheers for the suggestions and discussions folks.

**Pull request closed without merging**
