### PR TITLE
Add support for chance of precipitation

### PR DESCRIPTION
**Pull request by shortspider**
Need a new PR after #627 was removed.

### CODE REVIEW

**Comment by robinpaulson** [comment]
Thanks! As soon as I see v1.20 is working OK, I'll merge this.

**Comment by robinpaulson** [comment]
Much appreciated, I'll put out a new release in a week or so.

**Comment by robinpaulson** [comment]
The code didn't build after I added your PR, I wonder if you could take a look? I suspect it is a trivial failure we can ignore, but want to be sure.

**Comment by robinpaulson** [comment]
@igor-cali Do you recall how we were getting build errors the first time you submitted Spanish and Italian translations about two weeks ago? It appears we are getting the same errors again, from a different PR.

**Comment by shortspider** [comment]
@robinpaulson I just checked out the latest code and it builds fine for me. I'm just hitting make in android studio, are you doing something different?

**Comment by robinpaulson** [comment]
`./gradlew build`

Is the command in the github action to build it. It's a unit test failing, but I don't know why

**Comment by robinpaulson** [comment]
@shortspider I discovered a minor bug today in the code for this, could you take a look? See attached

**Pull request merged**
