### PR TITLE
Fix issue 346

### PR DESCRIPTION
**Pull request by igor-cali**
Fix [issue 346](https://github.com/martykan/forecastie/issues/346).

### CODE REVIEW

**Comment by robinpaulson** [comment]
I assume you mean move it to the right?

**Comment by igor-cali** [comment]
@robinpaulson the hard coded date was for testing the behaviour. It was not intended to be included in the final code. Thanks for noticing; I removed it.

**Comment by igor-cali** [comment]
@robinpaulson is there any other issue I shall resolve before merging?

**Comment by robinpaulson** [comment]
It looks all good now, cheers.

**Pull request merged**
