### PR TITLE
fix and add notification korean

### PR DESCRIPTION
**Pull request by BAESI**
I fix unit beacause Korean peoples use units in English and not in Korean. and I translated and added the notification.

+ The translation of the theme was also strange, so it was translated appropriately.

### CODE REVIEW

**Comment by robinpaulson** [comment]
Great! I looked back through the commit history, it appears another Korea-based student added the original translation almost exactly two years ago. I wonder if they were at the same university as you?

**Comment by BAESI** [comment]
She is my friend and colleague. I've been in the military for two years, so I'm taking a later class. I didn't know she contributed to this app.

**Comment by BAESI** [comment]
> 
She is my friend and colleague. I've been in the military for two years, so I'm taking a later class. I didn't know she contributed to this app.

**Comment by robinpaulson** [comment]
Hi, we had some problems which I reverted by doing a `git reset`, meaning we also lost your code. I'm afraid my `git` skills aren't that great, would you be able to re-propose this and I'll merge it in a couple of days? Thanks

**Comment by BAESI** [comment]
Hi! I'm working on another project right now, but I don't have much time left, so I think I'll have time over the weekend. Will that be okay?  if you okay, Should I do full request for Korean translation and UVindex fix?

**Comment by robinpaulson** [comment]
Hi, sorry @BAESI I forgot about this. It would be much appreciated if you could do the UVindex fix and the Korean translation fix. Cheers!

**Pull request merged**
