### PR TITLE
OWM certificate download for olded android versions (fix #487)

### LINKED ISSUE #487: Certificate expiry, API prior to 21
on below 21 devices the app opens and show the message network error please explain why it happens

### PR DESCRIPTION
**Pull request by fAntel**
Add downloading of OWM certificate if connection problems relates to certificate's CA trust. This issue occurs on Android 5 and below. For more information see #487

### CODE REVIEW

**Comment by robinpaulson** [comment]
Excellent, I'm very pleased to see this. Unfortunately the broader consequences of the changes are beyond my coding knowledge, and as it's an area which could affect security, I'm going to ask @FridoDeluxe and @igor-cali to take a look. I ask since they've contributed the most code over the last few years and likely have a better understanding of the code than I do.

Guys, would be you be able to cast your eyes over this PR please, I'm slightly nervous about the MITM possibilities, as discussed in #487?

Cheers

**Comment by igor-cali** [comment]
As far as I understand this PR change to code for all devices/Android versions.

Since issue #487 is limited on older Android versions (API previous than 21 / Lollipop as I understand) and since there are concerns on the security level of the patch, I would recommend to confine the improvement to those old devices and keep the current upstream code/behaviour for the rest of devices.

Code change proposal:
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP){ // consider the correct start version
  ... // Current upstream code
}
else {
  ... // Code in this @fantel PR
}

**Comment by fAntel** [comment]
It sounds reasonable. I've checked the last Forecastie version on emulators with Android SDK 15, 21 and 22 (Android versions 4.0.3, 5.0 and 5.1) and problem with certificate occurs on Android SDK 15 and 21.

Code change proposal has been added.

**Comment by robinpaulson** [comment]
> I would recommend to confine the improvement to those old devices

this sounds like a great idea

**Comment by FridoDeluxe** [comment]
Unfortunately I don't have any certificate experience on Android, so I can't have an reasonable opinion. But generally the PR looks good to me.

Is my assumption correct that the certificate is only downloaded/updated once a `SSLHandshakeException` is detected? And when the certificate is available all requests work normally?

**Comment by fAntel** [comment]
@FridoDelux yes, certificate is only downloaded/updated when SSLHandshakeException is detected. More precisely, when cause of SSLHandshakeException is problem with determining is certificate has been released by trusted CA. Because SSLHandshakeException could be trown for other reasone, for example, when time on the device is too different from the server (like request from the future or past). I tried this fix on emulators for API 15 and 21 with disabled and enabled Internet connection (to check is IOException parsed correctly) and it helps. And I try it for API 22 to check that it doesn't break something.

**Pull request merged**
