### PR TITLE
Fix bug when searching for city; add temporary text hint to "Graphs" button

### PR DESCRIPTION
**Pull request by lmaths**
Hi, I'm sending a pull request with the solution I found for this issue. I check if it is the first application run and display the message "Tap for Graphs", and fix bug on search for city.

### CODE REVIEW

**Comment by robinpaulson** [comment]
Hi, thanks for this, I'm pleased to see a new coder joining in! Could you do me a little favour and attach a screenshot? Cheers

**Comment by robinpaulson** [comment]
At some point we'll have to make it translateable too, by putting the text "Tap for graphs" into values/strings.xml, but we can leave that for the moment.

**Comment by lmaths** [comment]
Hello, thank you for the opportunity, it is incredible to contribute and learn from the community. I will be active participating in the project. Of course, below are some screenshots.

On the user's first run, the message "Tap for Graphs" is displayed below the button.
image

After the first run, we no longer display the message.
image

**Comment by lmaths** [comment]
> At some point we'll have to make it translateable too, by putting the text "Tap for graphs" into values/strings.xml, but we can leave that for the moment.

It is true! I forgot this detail but I can solve it next time.

**Comment by lmaths** [comment]
about the bug when searching for city, just a .trim () to remove spaces in the string serves us.

**Comment by robinpaulson** [comment]
It's looking great!
This might sound picky, but would it be possible to move the text up slightly, so it's above the icon? And give it a bit of contrast to the cloud, by changing the colour.

It crossed my mind we should check how it looks under multiple themes, but is a new user likely to change theme before they see the "Tap for Graphs" label? Perhaps not, what do you think?

**Comment by robinpaulson** [comment]
> Hello, thank you for the opportunity, it is incredible to contribute and learn from the community. I will be active participating in the project.

No need to be thankful: we all gain, I'm glad to have more devs interested

I'm also pleased to hear you're keen to do further development on it.

**Comment by robinpaulson** [comment]
> It is true! I forgot this detail but I can solve it next time.

Great, yes, for the next PR

**Comment by lmaths** [comment]
Hi @robinpaulson, I made some changes, added a more attractive color to the cloud and to the text and that color follows the pattern of the rest according to the themes.
I added the text in the strings.xml and also translated it into Portuguese - Brazil.
And I adjusted the possibility for the user to change the theme before seeing the message, now it is displayed when changing the theme and then disappears.
What do you think?

**Comment by robinpaulson** [comment]
The work you've done sounds great, I'm happy to see this. Could you provide a screenshot again?

**Comment by robinpaulson** [comment]
I don't usually ask for screens, but this a relatively crowded part of the app already, making sure things are arranged carefully is important.

**Comment by robinpaulson** [comment]
It's not a comment on your coding or decision-making.

**Comment by robinpaulson** [comment]
> Hi @robinpaulson, I made some changes, added a more attractive color to the cloud and to the text 
> and that color follows the pattern of the rest according to the themes.

this is great to hear, I'm glad you used the existing themes.

> I added the text in the strings.xml and also translated it into Portuguese - Brazil.

Excellent!

> And I adjusted the possibility for the user to change the theme before seeing the message, now it 
> is displayed when changing the theme and then disappears.

Good to hear, this is all going very well.

**Comment by lmaths** [comment]
> 
> 
> I don't usually ask for screens, but this is a relatively crowded part of the app already; making sure things are arranged carefully is important.

No problem, you are right, we need to ensure that everything works correctly and with high quality!
I'll send you some screenshots.

**Comment by lmaths** [comment]
When the user opens the app the first time, notice the colors compared to before.
image

When the appearance is changed, the color is changed as, and the message is displayed
image

In portuguese
image

What do you think? if you have any observation tell me that i will be adjusting

**Comment by robinpaulson** [comment]
It's an improvement. I'd like to see the "Tap for Graphs" text symmetrical under the weather icon, but that may be more difficult than it appears. I'll accept this for now, we can work on the specifics later. I'll also put out a new version soon.

I just thought: will the text display for those who already have it installed and that get the upgrade in the next day or so? I'm sure there are many who have it installed who don't know this function exists.

Cheers

**Comment by lmaths** [comment]
Yes, users who already have the application will also receive the "touch for graphics" alert, as if it were the first execution, because in their source code they do not have the logic for it.
olverlaid text in icon I thought it was not so readable, but then I can try to improve.

**Comment by robinpaulson** [comment]
> overlaid text in icon I thought it was not so readable

Ah, that changes things i guess. Did you try it with different coloured text, something darker?

**Comment by lmaths** [comment]
image
Look, have any suggestions?

**Comment by lmaths** [comment]
image
or something like this?

**Comment by robinpaulson** [comment]
Yeah, that looks bad. Maybe white text with a black outline?

**Comment by robinpaulson** [comment]
No, scrub that, it'll disappear against the background.

**Comment by robinpaulson** [comment]
OK, we'll go with your original layout. Centrally-placed under the icon.

**Comment by lmaths** [comment]
image

**Comment by lmaths** [comment]
> 
> 
> No, scrub that, it'll disappear against the background.

Precisely, in the part that has the cloud it is ok but in the background part it is bad

**Comment by robinpaulson** [comment]
I tried tapping on the area underneath the icon, about where you had put the text. No response. It appears it only works by clicking on the icon itself. So, either we make the colours work, or expand the clickable area. What do you think?

**Comment by lmaths** [comment]
I will add the click in the total area

**Comment by lmaths** [comment]
Done! try now 👍

**Comment by robinpaulson** [comment]
It's OK, I trust you, I'm sure it's great. I'll merge it later, in case anything springs to mind. I'm not doing a release now anyway, it's late here!

**Comment by lmaths** [comment]
Thanks, if you think of anything we can modify, let me know and we'll work on it! See you later.

**Comment by robinpaulson** [comment]
OK, we've both sat on this for a while and nothing has come to mind. I'll merge and do a release.

**Comment by robinpaulson** [comment]
The new version dropped a few minutes ago. It works fine, problem is it doesn't disappear after the first time I use it. Could you take a look, see what's happening @lmaths?

**Comment by robinpaulson** [comment]
If I kill the app then restart it, the hint text is gone. That's not what I was after though, some people will only reboot their phone sporadically; I'm not sure how many would force quit it, I'd guess not so many.

**Comment by lmaths** [comment]
@robinpaulson I'll adjust the logic for when the user clicks the button, later I'll send a pull request adjusting this

**Comment by robinpaulson** [comment]
Hi @lmaths how are you getting on with this, I'm going to make a new release in a week or so?

**Comment by lmaths** [comment]
hi @robinpaulson i'm sorry, i'll send a pull request today!

**Pull request merged**
