### PR TITLE
SDK upgrade / Remove Dashclock

### PR DESCRIPTION
**Pull request by igor-cali**
#509 --> Upgrade to Android 10 / SDK 29
#524 --> Migration to AndroidX
#518 --> Dashclock removed
Italian translation updated

### CODE REVIEW

**Comment by fAntel** [comment]
I've migrated to AndroidX today too. Some points:
1. `'androidx.legacy:legacy-support-v4:1.0.0'` could be replaced with `"androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"`. This contains all explicit imports from `legacy-support`.
2. I think behavior of Recycler View has been changed in AndroidX because after migration rows in recycler views at MainActivity get higher. We need to change the root `layout_height` in `list_row.xml` to `wrap_content`.
3. Do we need `appcompat` as explicit dependency? There are no explicit imports in the code and it is already included in `material` library.
4. Should we upgrade libraries to the latest versions?
- `appcompat` to 1.2.0
- `constraintlayout` to 2.0.1
- `recyclerview` to 1.1.0
- `material` to 1.2.1

And during check after migration I've found some bugs. I'll post them as separate pull request.

**Comment by igor-cali** [comment]
> I've migrated to AndroidX today too. Some points:
> 
>     1. `'androidx.legacy:legacy-support-v4:1.0.0'` could be replaced with `"androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"`. This contains all explicit imports from `legacy-support`.
> 
>     2. I think behavior of Recycler View has been changed in AndroidX because after migration rows in recycler views at MainActivity get higher. We need to change the root `layout_height` in `list_row.xml` to `wrap_content`.
> 
>     3. Do we need `appcompat` as explicit dependency? There are no explicit imports in the code and it is already included in `material` library.
> 
>     4. Should we upgrade libraries to the latest versions?
> 
> 
>     * `appcompat` to 1.2.0
> 
>     * `constraintlayout` to 2.0.1
> 
>     * `recyclerview` to 1.1.0
> 
>     * `material` to 1.2.1
> 
> 
> And during check after migration I've found some bugs. I'll post them as separate pull request.

Thanks @fAntel . Please propose your PR. I am closing this one and redo the other changes afterwards.

**Comment by robinpaulson** [comment]
i cherry-picked the italian translation; i would have taken more but the dashclock removal was tangled up with the androidx changes

**Comment by robinpaulson** [comment]
I removed dashclock too. Maybe some mistakes though....

**Pull request closed without merging**
