### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by JigarSable**

### CODE REVIEW

**Comment by sotpapathe** [comment]
Does this update solve any issues? Forcing a newer gradle version might leave people with older systems unable to compile. I'm not against the change, just making sure we have thought about any potential problems before updating dependencies.

**Comment by robinpaulson** [comment]
@sotpapathe This is a good point. @JigarSable could you research the consequences of the Gradle upgrade please and let us know here? Thanks

**Comment by JigarSable** [comment]
@sotpapathe You are right this update may change code compatibility. Thank You

**Comment by sotpapathe** [comment]
@JigarSable Thanks for looking into it!

**Pull request closed without merging**
