### PR TITLE
Fix UVIndex bug and korean translate

### PR DESCRIPTION
**Pull request by BAESI**
I'm sorry for the confusion. I created a new repertoire, modified the code, and checked that this app is working normally.

### CODE REVIEW

**Comment by robinpaulson** [comment]
It appears @hockdudu has fixed the UV bug, although it might he a while until the PR he has suggested is merged. #643

**Comment by robinpaulson** [comment]
If you remove that commit from the PR, I'll gladly accept the other.

**Comment by robinpaulson** [comment]
I assume #642 is redundant and can be closed?

**Comment by BAESI** [comment]
I am also happy that I had the opportunity to correct these problems.  : )  I close this PR

**Comment by robinpaulson** [comment]
And propose another PR with just the Korean translations?

**Pull request closed without merging**
