### PR TITLE
refactoring comparison statement

### PR DESCRIPTION
**Pull request by yonniii**
I refactored the code to check whether it's the same.
I think it improve readability!. :)

### CODE REVIEW

**Comment by robinpaulson** [comment]
Does this achieve anything beyond readability? Readability is important of course.

**Comment by yonniii** [comment]
This makes the code more reliable. It can prevent references to 'null'.

**Comment by robinpaulson** [comment]
I'm not sure I know much about that, could you expand please? Or point me to an explantation or example elsewhere?

**Comment by yonniii** [comment]
String language = Locale.getDefault().getLanguage();
        if (language.equals("cs")) {
            language = "cz";
        }

For example, in this case, if var language is null, language.equals("cs") cause error.

**Comment by yonniii** [comment]
String language = Locale.getDefault().getLanguage();
        if (language.equals("cs")) {
            language = "cz";
        }

For example, in this case, if var language is null, language.equals("cs") cause error.

**Comment by robinpaulson** [comment]
You didn't have to close this, I'm willing to accept it, I wanted an explanation of why it was important, that's all.

**Comment by yonniii** [comment]
I heard that Korean companies recommend this to avoid exceptions. But I'm a student, I'm not sure this is a good way. I'm sorry. If you don't agree, you don't have to accept it. Thank. :)

**Comment by robinpaulson** [comment]
I don't know either. If you think you have a good argument, make it. Convince me.

**Comment by yonniii** [comment]
Hi, I've thought about it, but I don't think you need to accept this. I changed the code for fear of referring to null. But it is enough to confirm null. So there's no need to fix it. Thank you for considering my opinion!

**Comment by FridoDeluxe** [comment]
In fact the oder of `equals` comparison is not consistent in the current Forecastie code. Unlike @yonniii I'm personally in favor of putting the string literal at the end, but I guess readability is in this case rather subjectively biased.

Having the string literal first will avoid NullPointer exceptions. But on the other hand without any exception a null object will never be detected, so the `equals` comparison itself is not a complete solution for handling null values in my opinion.

**Comment by robinpaulson** [comment]
@fridodeluxe do you think there is value in fixing either or both the points you raise?

**Comment by FridoDeluxe** [comment]
As long as there are no bug reports I see no need for handling potential null values implicitely or explicitely in these cases. Apart from that it's only about readability and there I'm prejudiced as a fan of variable-first-literal-second :smile:.

**Comment by robinpaulson** [comment]
Is there a consensus in the java/android (or any) community about the order of variables and literals?

**Comment by FridoDeluxe** [comment]
Literals-first is called _yoda condition_ for a reason, it's not the natural order of comparisons in code (for other things like null checks or mathematical comparison I only know variable-first). So for me it doesn't improve readabilty.

And although it implicitly prevents `NullPointerExceptions` literals-first is not a good general programming habit - that's what I get from reading all the pros and cons on https://stackoverflow.com/questions/20385179/calling-equals-on-string-literal. If you really want to prevent null values it's probably better to do a check explicitly - literals-first won't prevent all null situations and for others it's not clear if the `equals` is there to check nulls or just to compare strings.

**Comment by robinpaulson** [comment]
@FridoDeluxe In this case, do you think it is worth the effort and lines of code to check for NULL values in all situations? How likely is it that they will come up in the data? Maybe we should fix that first, before addressing the literals/variables first question?

**Comment by FridoDeluxe** [comment]
Null values are not likely here, they come from the Preferences and these are mostly lists of predefined values. As long as there are no bug reports there is no need for an additional check.

**Comment by robinpaulson** [comment]
Right, in that case us it worth recommending a consistent style? Is the code likely already OK?

**Comment by robinpaulson** [comment]
Closing, probably not necessary or relevant.

**Comment by FridoDeluxe** [comment]
It's probably too detailed to recommend a consistent style for exactly this case. _... consistent with the existing code_ should be enough for now. Both linked Style Guides (Google and Android) don't mention the order of `equals`.

**Pull request closed without merging**
