### PR TITLE
Added a Swedish translation.

### PR DESCRIPTION
**Pull request by Aresiel**
On a side note, the ssh keys I deleted wont get you anywhere. I accidentally created them.

### CODE REVIEW

**Comment by FridoDeluxe** [comment]
_Tack så mycket!_ Astonishing that there wasn't Swedish translation so far.

But one thing: Strings marked with `translatable="false"` must not be translated into the other languages. These entries must be removed when you copy the default `strings.xml`.

**Comment by robinpaulson** [comment]
@FridoDeluxe Is this a flaw which needs correcting before the pull is accepted?

**Comment by Aresiel** [comment]
Oh, ok FridoDeluxe

**Comment by Aresiel** [comment]
I'll remove it, I only think there's one btw

**Comment by Aresiel** [comment]
I removed them @FridoDeluxe

**Comment by robinpaulson** [comment]
@FridoDeluxe Are the translatable="false" issues fixed?

**Comment by FridoDeluxe** [comment]
Yes, looks good now, Thanks, @Aresiel!

Background: Not translatable strings (which have the same value independent of language) are meant to exist only in the default translation. Otherwise this leads to problems, for instance a new release with a new version number displays the wrong outdated old version number from the Swedish translation.

**Comment by Aresiel** [comment]
Cool! Then I guess merging comes next?

**Pull request merged**
