### PR TITLE
add the graph for humidity

### PR DESCRIPTION
**Pull request by SIMSEUNGMIN**

### CODE REVIEW

**Comment by robinpaulson** [comment]
I'll accept this, but as I discussed with @FridoDeluxe recently (#218), we will likely have to provide controls for selecting the weather the users wants to see, the screen is getting more and more crowded.

**Comment by SIMSEUNGMIN** [comment]
I understand your answer. you want to make the new function selecting the graph when users push the "graph". Is it right?

**Comment by SIMSEUNGMIN** [comment]
> I'll accept this, but as I discussed with @FridoDeluxe recently (#218), we will likely have to provide controls for selecting the weather the users wants to see, the screen is getting more and more crowded.

I understand your answer. you want to make the new function selecting the graph when users push the "graph". Is it right?

**Comment by SIMSEUNGMIN** [comment]
I understand your answer. you want to make the new function selecting the graph when users push the "graph". Is it right?

**Comment by robinpaulson** [comment]
There are lots of pieces of information on the screen at once. We have plans to add more (ultra violet, pollution, real feel temperature). We should make the screen configurable so the user can add and remove information they want to see, making the screen less complicated. Not yet, but in the near future.

The pull request you made is great, however we should think ahead.

**Pull request merged**
